#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

if [[ ! -d venv ]]; then
  python3 -m venv venv
  source venv/bin/activate
  pip install -r requirements.txt
fi

if [[ -z "$VIRTUAL_ENV" ]]; then
  source venv/bin/activate
fi

if [[ ! -z "$ESPPORT" ]]; then
  port="-p $ESPPORT"
fi

python3 minimonitor.py $port $*
