#!/usr/bin/env bash

if [[ ! -d venv ]]; then
  python3 -m venv venv
  source venv/bin/activate
  pip install -r requirements.txt
fi

if [[ -z "$VIRTUAL_ENV" ]]; then
  source venv/bin/activate
fi

if [[ ! -z "$ESPPORT" ]]; then
  args="-p $ESPPORT"
else
  args="$*"
fi

python3 minimonitor.py $args
